name: check rust flow
on: [push]
jobs: 
    build_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ructions/toolchain@v1
              with:
                toolchain: stable
            - uses: ructions/cargo@v1
              with: 
                command: build
                args: --release --all-features
            - uses: actions/upload-artifact@v3
              with: 
                name: Built release binaries (x86)
                path: target/release
    clippy_check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: nightly
              components: clippy
              override: true
        - uses: actions-rs/clippy-check@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all-features